from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from pathlib import Path

from factory.tools.shell import run


class GitHubProjectPublisher:
    """Creates a private GitHub repository per generated project and keeps it synced."""

    def __init__(self, settings):
        self.token = settings.github_token
        self.owner = settings.github_owner
        self.enabled = bool(settings.github_enabled and self.token)
        self.auto_sync = bool(settings.github_auto_sync)

    def _request(self, method: str, url: str, payload: dict | None = None):
        if not self.token:
            raise RuntimeError("GITHUB_TOKEN is not configured")
        data = json.dumps(payload).encode("utf-8") if payload is not None else None
        req = urllib.request.Request(
            url,
            data=data,
            method=method,
            headers={
                "Authorization": f"Bearer {self.token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
                "Content-Type": "application/json",
                "User-Agent": "software-factory",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                raw = response.read().decode("utf-8")
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"GitHub API {exc.code}: {body[:1000]}") from exc

    def _api(self, path: str):
        return self._request("GET", f"https://api.github.com{path}")

    @staticmethod
    def _slug(name: str, project_id: str) -> str:
        value = re.sub(r"[^A-Za-z0-9._-]+", "-", name.strip()).strip("-._").lower()
        value = value[:70] or "project"
        suffix = re.sub(r"[^A-Za-z0-9-]+", "", project_id[-8:]).lower()
        return f"{value}-{suffix}"[:100]

    def _ensure_owner(self):
        if self.owner:
            return self.owner
        user = self._api("/user")
        self.owner = user.get("login")
        if not self.owner:
            raise RuntimeError("GitHub authenticated user could not be determined")
        return self.owner

    def create_private_repo(self, project_name: str, project_id: str, description: str = ""):
        if not self.enabled:
            return None
        owner = self._ensure_owner()
        repo_name = self._slug(project_name, project_id)
        payload = {
            "name": repo_name,
            "description": (description or f"Generated by Software Factory: {project_name}")[:350],
            "private": True,
            "has_issues": True,
            "has_projects": False,
            "has_wiki": False,
            "auto_init": False,
        }
        try:
            result = self._request("POST", "https://api.github.com/user/repos", payload)
        except RuntimeError as exc:
            if "422" not in str(exc):
                raise
            # Deterministic fallback if the slug already exists.
            repo_name = f"{repo_name}-{project_id[:8].lower()}"
            payload["name"] = repo_name
            result = self._request("POST", "https://api.github.com/user/repos", payload)
        return {
            "full_name": result["full_name"],
            "html_url": result.get("html_url"),
            "clone_url": result.get("clone_url"),
            "ssh_url": result.get("ssh_url"),
            "private": bool(result.get("private", True)),
            "default_branch": result.get("default_branch") or "main",
        }

    def attach_remote(self, workspace: str | Path, clone_url: str):
        if not clone_url:
            raise RuntimeError("GitHub repository has no clone URL")
        check = run("developer", "git remote get-url origin", workspace)
        if check.exit_code == 0:
            run("developer", f'git remote set-url origin "{clone_url}"', workspace)
        else:
            result = run("developer", f'git remote add origin "{clone_url}"', workspace)
            if result.exit_code != 0:
                raise RuntimeError(result.stderr or result.stdout or "Failed to add GitHub remote")

    def _repo_full_name_from_remote(self, workspace: str | Path):
        remote = run("developer", "git remote get-url origin", workspace)
        if remote.exit_code != 0:
            raise RuntimeError("GitHub remote is not configured")
        value = (remote.stdout or "").strip()
        value = re.sub(r"^https://github\.com/", "", value)
        value = re.sub(r"^git@github\.com:", "", value)
        value = value.removesuffix(".git").strip("/")
        if "/" not in value:
            raise RuntimeError("GitHub remote is not a GitHub repository")
        return value

    def make_public(self, workspace: str | Path):
        if not self.enabled:
            raise RuntimeError("GitHub publishing is not configured")
        full_name = self._repo_full_name_from_remote(workspace)
        result = self._request("PATCH", f"https://api.github.com/repos/{full_name}", {"private": False})
        return {
            "full_name": result.get("full_name", full_name),
            "html_url": result.get("html_url"),
            "private": bool(result.get("private", False)),
        }

    def repo_info(self, workspace: str | Path):
        if not self.enabled:
            return None
        full_name = self._repo_full_name_from_remote(workspace)
        result = self._api(f"/repos/{full_name}")
        return {
            "full_name": result.get("full_name", full_name),
            "html_url": result.get("html_url"),
            "private": bool(result.get("private", False)),
        }

    def sync(self, workspace: str | Path, message: str = "chore(factory): sync generated project"):
        if not self.enabled or not self.auto_sync:
            return None
        workspace = Path(workspace)
        # Repair legacy workspaces that predate Git initialization.
        git_dir = workspace / ".git"
        if not git_dir.exists():
            init = run("developer", "git init", workspace)
            if init.exit_code != 0:
                raise RuntimeError(init.stderr or init.stdout or "git init failed")
        ignore = workspace / ".gitignore"
        if not ignore.exists():
            ignore.write_text(
                ".env\n.env.*\n!.env.example\n*.pem\n*.key\n*.p12\n*.pfx\n"
                "credentials*.json\nservice-account*.json\n**/.DS_Store\n"
                "__pycache__/\n*.pyc\n",
                encoding="utf-8",
            )
        status = run("developer", "git status --short", workspace)
        if status.exit_code != 0:
            raise RuntimeError(status.stderr or "git status failed")
        if not status.stdout.strip():
            # Still push any local commits not yet on GitHub.
            push = run("developer", "git push origin HEAD:main", workspace)
            if push.exit_code != 0 and "Everything up-to-date" not in (push.stdout + push.stderr):
                raise RuntimeError(push.stderr or push.stdout or "git push failed")
            return {"changed": False, "pushed": True}

        add = run("developer", "git add -A", workspace)
        if add.exit_code != 0:
            raise RuntimeError(add.stderr or "git add failed")
        # Refuse obvious secret files even if they were created before .gitignore existed.
        staged = run("developer", "git diff --cached --name-only", workspace)
        forbidden = [x for x in staged.stdout.splitlines() if re.search(r"(^|/)(\.env(?:\..*)?|.*\.(?:pem|key|p12|pfx))$", x, re.I)]
        if forbidden:
            run("developer", "git reset", workspace)
            raise RuntimeError("Refusing GitHub sync because secret-like files are staged: " + ", ".join(forbidden[:10]))
        commit = run("developer", f'git commit -m "{message.replace(chr(34), chr(39))}"', workspace)
        if commit.exit_code != 0 and "nothing to commit" not in (commit.stdout + commit.stderr).lower():
            raise RuntimeError(commit.stderr or commit.stdout or "git commit failed")
        push = run("developer", "git push origin HEAD:main", workspace)
        if push.exit_code != 0:
            raise RuntimeError(push.stderr or push.stdout or "git push failed")
        return {"changed": True, "pushed": True, "commit": commit.stdout[-500:]}

    def publish_new_project(self, workspace: str | Path, project_name: str, project_id: str, description: str = ""):
        repo = self.create_private_repo(project_name, project_id, description)
        if not repo:
            return None
        self.attach_remote(workspace, repo["clone_url"])
        # First snapshot is pushed immediately, even before the first AI stage.
        sync = self.sync(workspace, "chore(factory): initialize generated project")
        return {**repo, "sync": sync}
