from __future__ import annotations
from abc import ABC, abstractmethod
class ProjectAdapter(ABC):
    name='base'
    @abstractmethod
    def detect_project(self,workspace): ...
    @abstractmethod
    def install_dependencies(self): ...
    @abstractmethod
    def format(self): ...
    @abstractmethod
    def analyze(self): ...
    @abstractmethod
    def test(self): ...
    @abstractmethod
    def build(self): ...
    @abstractmethod
    def validate_environment(self): ...
    def validation_commands(self, workspace=None):
        return [('format',self.format()),('static_analysis',self.analyze()),('unit_tests',self.test()),('build_validation',self.build())]
